spring:
  application:
    # 应用名称
    name: juwuhe-back

  #数据配置相关
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: juwuhe-blog
    # 数据库连接地址
    url: jdbc:mysql://112.126.64.206:3306/juwuhe-blog?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: xishi145678

# 应用服务 WEB 访问端口
server:
  port: 11528

#Mybatis-plus-日志服务
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

